### ISSUE TITLE
deleting an exhibit gives an error

### ISSUE THREAD

**Issue by roxannewyns** [libis/Espace#25]
assigned @JorisLambrechts 
cc @naeemmuhammad 

when I delete an exhibit (logged in as admin) I get an error message. When I go back, the exhibit is deleted anyway.  

Catchable fatal error: Object of class Exhibit could not be converted to string in ...

**Comment by JorisLambrechts** [comment]
@naeemmuhammad there is a problem in the Libco plugin: Object of class Exhibit could not be converted to string in /plugins/Libco/models/LibcoService.php on line 161

It's the function prepareUrl($recordKey). I'm guessing the $recordKey is still the record object and not the id.

**Comment by naeemmuhammad** [comment]
This was an ongoing implementation of the Data Adapter for integration of Omeka with VEP Repository. Data adapter intercepted (by Omeka hooks)  the deletion of exhibits in order to delete them from the VEP Repository, that was causing the problem. Now that we do not plan to use data adapter for Omeka VEP integration, i have removed these hooks. Fix: 677da8cc6ed38266bd839c733548dbb73a004cb9

LibCo plugin is not needed for Data adapter anymore, therefore i am using it now for Europeana Space api.
